version: '3'

services:

  redis-master:
    image: redis:latest
    restart: always
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: wordle
      POSTGRES_PASSWORD: wordle
      POSTGRES_DB: wordle
    ports:
      - "5432:5432"
